### PR TITLE
Support Redactor-fields in django admin inlines

### PR DESCRIPTION
**Pull request by akadan47**
Editor's fields was displayed, but didn't work in django admin inlines.
I fix this...

### CODE REVIEW

**Comment by mazelife** [comment]
I'm having some issues reproducing this problem. What browser are you using? 
I created a test Django app with an inline that had a redactor widget, and everything seems to work fine, at least in Safari and FireFox. The inline fields have the redactor editor in the admin and the page saves properly. Switching to your branch seems to change the styling with respect to the field labels, but otherwise I don't see a difference. Can you provide more detail on exactly the problems you were encountering?

**Comment by akadan47** [comment]
The problem occurs when you add inline (by click on the button "Add another <>"). 

In django admin, inlines are added by cloning hidden (empty) inline form template. Editor also cloned and displayed well, but the buttons in toolbar do not work. 

I see this problem in all browsers that I use (Safari, Chrome, Firefox, Opera).

**Comment by mazelife** [comment]
Ah, yes! That makes perfect sense. Adding new inlines was something I neglected to account for in my JavaScript. I'll take a look at this again and try to get it merged quickly.

**Comment by mazelife** [comment]
OK, I went ahead and merged this manually: https://github.com/mazelife/django-redactoreditor/commit/a179d8e2e180f277f8008a73e4221b761dde9217

I was hoping to find a way around using DOMNodeInserted, since that means we lose IE < 9, but after studying the inline.js code in the admin app, it looks like there is absolutely no way to plug-in to what they are doing. So, I went ahead and used your fix. Thanks for the contribution!

**Comment by akadan47** [comment]
Hi, James!

I removed that hack with "DOMNodeInserted" event and it seems it all works, but editor (redactor.js) does not work in IE<9 anyway (I tested in IE in a virtual machine). 
https://github.com/akadan47/django-redactoreditor/commit/cc1679e372bed414a7ca0307887d3c613594a474

Also i fixed a bug with hiding (overflow:hidden) dropdown menus in django admin (when height of editor's field is small).
https://github.com/akadan47/django-redactoreditor/commit/5547fb9f383b4c0d5fb417cc52b5991b9227bca7

**Comment by mazelife** [comment]
Thanks for checking in IE; I don't have access to that browser at the moment.  I went ahead and cherry picked those two commits from your fork, so they're in master now.

**Pull request closed without merging**
